---
- name: Install Java
  hosts: jenkins
  become: yes
  roles:
    - geerlingguy.java
- name: Install Jenkins
  hosts: jenkins
  vars:
    jenkins_url_prefix: "/jenkins"
    jenkins_prefer_lts: true
    jenkins_java_options: ""
  become: yes
  roles:
    - geerlingguy.jenkins